### PR TITLE
Add reset component button

### PR DESCRIPTION
**Pull request by mzlarsson**

### CODE REVIEW

**Comment by AntonNeld** [comment]
Like the "stop effect" button, this is also dangerous. Should we require the same kind of double click here? I guess there is less chance to misclick, but the consequences are worse.

**Comment by mzlarsson** [comment]
Might be a good idea! Will add that.

**Comment by mzlarsson** [comment]
Added support for double-click procedure and a restart button

**Review by AntonNeld — APPROVED** [review]
Conditional on fixing eslint warning

**Pull request merged**
